Update pi-apps-unauth

diff --git a/pi-apps-unauth b/pi-apps-unauth
--- a/pi-apps-unauth
+++ b/pi-apps-unauth
@@ -20,13 +20,13 @@ if uname -m | grep -qi 'x86\|i686\|i386' ;then
   error "Pi-Apps is not supported on non-ARM CPU architectures. We encourage you to use your distro's app store, like Gnome Software or Discover Software Center."
 fi
 
-sudo apt update --allow-unauthenticated || error "The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system."
+sudo apt update --allow-insecure-repositories || error "The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system."
 
 #install dependencies
 dependencies='yad curl wget aria2 lsb-release software-properties-common apt-utils apt-transport-https gnupg imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils rsync unzip debsums libgtk3-perl'
 
 if ! dpkg -s $dependencies &>/dev/null ;then
-  sudo apt install $dependencies -y -f --no-install-recommends --allow-unauthenticated || error "Pi-Apps dependencies failed to install and so the Pi-Apps install has been aborted. Before Pi-Apps can be installed you must solve any errors above."
+  sudo apt install $dependencies -y -f --no-install-recommends --allow-insecure-repositories || error "Pi-Apps dependencies failed to install and so the Pi-Apps install has been aborted. Before Pi-Apps can be installed you must solve any errors above."
 fi
 
 #remove annoying "YAD icon browser" launcher
